# Generated by Django 6.0.4 on 2026-04-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, help_text='مثلاً: أسود ملكي، ذهبي', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, help_text='مثلاً: حرير، جلد طبيعي', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, help_text='مثلاً: XL, 42, Large', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='technical_specs',
            field=models.TextField(blank=True, help_text='أي مواصفات إضافية أخرى تودين ذكرها', null=True),
        ),
        migrations.DeleteModel(
            name='ProductSpecification',
        ),
    ]
