# Generated by Django 6.0 on 2026-06-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_product_is_approved_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_disbursed',
            field=models.BooleanField(default=False),
        ),
    ]
