# Generated by Django 6.0 on 2026-06-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_order_customer_latitude_order_customer_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='vendor_ready',
            field=models.BooleanField(default=False, help_text='Vendor has marked this item ready'),
        ),
    ]
