# Generated by Django 6.0 on 2026-06-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_vendor_ready_to_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
    ]
