# Generated by Django 6.0.4 on 2026-06-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_influencerad'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_account',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='driving_license',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.ImageField(blank=True, null=True, upload_to='national_ids/'),
        ),
        migrations.AddField(
            model_name='user',
            name='resume',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='social_links',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='specialty',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
