# Generated by Django 6.0.4 on 2026-06-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_adpurchase_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('marketing_accepted', 'Demande marketing acceptée'), ('wallet_credit', 'Argent reçu'), ('ad_purchase', 'Annonce achetée'), ('new_order', 'Nouvelle commande'), ('driver_rating', 'Avis client')], max_length=30),
        ),
    ]
