# Generated by Codex on 2026-07-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='influencer_ad',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='core.influencerad',
            ),
        ),
    ]
